### ISSUE TITLE
Add "Back to Top" Button

### ISSUE THREAD

**Issue by marisabrantley** [niegfg/amazon-clone#23]
I'd like to add a "Back to Top" button/bar above the footer, just as Amazon has.

Please assign this to me.

<img width="1290" alt="back-to-top-bar" src="https://user-images.githubusercontent.com/60168324/194736257-d24fd450-06c6-456e-9747-845788fc2044.png">

**Comment by marisabrantley** [comment]
...with the Hacktoberfest labels. Thank you!

**Comment by ahmadsohail404** [comment]
go ahead :)
