### ISSUE TITLE
Please make cursor to pointer when we hover and also add project link in about section

### ISSUE THREAD

**Issue by Saran-pariyar** [niegfg/amazon-clone#4]
**First of all please add your project link to the about section so that contributors can visit the project as soon as they visit the repo**

### Add link here : 
![Screenshot from 2022-10-08 20-16-54](https://user-images.githubusercontent.com/86418083/194712805-8adb5131-7849-4602-98f0-229b0873ebd2.png)

**Comment by ahmadsohail404** [comment]
Thanks for the suggestion. The links have been added! cursor things need to be fixed as an issue by the contributors as the contribution increases and the project goes further
