### ISSUE TITLE
Add Carousel to Home page

### ISSUE THREAD

**Issue by rahul-n18** [niegfg/amazon-clone#44]
Add Carousel to Home page: 
![Screenshot (67)](https://user-images.githubusercontent.com/64891042/195080402-944dd66a-e950-4729-b942-9a1ecae5abd1.png)

**Comment by rahul-n18** [comment]
I would love to work on this

**Comment by ahmadsohail404** [comment]
go ahead

**Comment by rahul-n18** [comment]
Im sorry I'm currently caught up with some other things I cannot Contribute.

Have a good day
