### ISSUE TITLE
Change "OnClick" effect on the link.

### ISSUE THREAD

**Issue by trats08** [niegfg/amazon-clone#49]
By clicking upon the links shown in the 'inspired by your browsing history', the onclick effect can be enhanced for better UI experience instead of showing dull background for that section.

Kindly assign me this issue and add the Hactoberfest label. 

![Screenshot (3)](https://user-images.githubusercontent.com/98650058/195114392-014ed7fb-643a-4b87-b01b-f01591158614.png)

**Comment by ahmadsohail404** [comment]
go ahead
