### ISSUE TITLE
Put pointer cursor in the page wherever necessary

### ISSUE THREAD

**Issue by ahmadsohail404** [niegfg/amazon-clone#5]

**Comment by 1-Rishabh-Jain-1** [comment]
Can you please assign this issue to me?

**Comment by shashi3000** [comment]
can u assign me this, please?

**Comment by M-Rahul1** [comment]
I Would like to contribute.
![Screenshot (16)](https://user-images.githubusercontent.com/68385075/194714770-184ace95-c676-40f1-82ea-c53595875040.png)

**Comment by ahmadsohail404** [comment]
Go ahead!!

**Comment by YugalPradhan** [comment]
Hey @ahmadsohail404  can you assign me this, I will do it asap

**Comment by ElvinPero** [comment]
I have resolved this issue.  Check my pull request #10  for this issue #5

**Comment by sumitbaroniya** [comment]
please assign me this issue.
